### ISSUE TITLE
Kernel 3.14 compilation problem

### ISSUE THREAD

**Issue by tbarbette** [kohler/click#133]
Hi,

I saw a commit which should update the compatibility to kernel 3.15, so I imagine it should work with 3.14 (tried with gcc 4.8 and 4.9) . But I've got this compilation problem : 

```
$ make
make[1]: Entering directory `/home/tom/click-kernel/linuxmodule'
echo "linuxmodule  analysis app aqm ethernet icmp ip simple standard tcpudp test threads" | ../click-buildtool findelem -r linuxmodule -p .. -X ./elements.exclude --checksum elements.csmk > elements.conf
../click-buildtool elem2make --linux -x "addressinfo.o alignmentinfo.o errorelement.o portinfo.o scheduleinfo.o" < elements.conf > elements.mk
../click-buildtool elem2export < elements.conf > elements.cc
make -C /usr/src/linux-source-3.14/ M=/home/tom/click-kernel/linuxmodule  modules
make[2]: Entering directory `/usr/src/linux-source-3.14'
  CC [M] crc32.o
  CC [M] in_cksum.o
  CXX [M] string.o
  CXX [M] straccum.o
  CXX [M] nameinfo.o
In file included from /home/tom/click-kernel/include/click-linuxmodule/include2/linux/kernel.h:18:0,
                 from /home/tom/click-kernel/linuxmodule/../include/click/glue.hh:23,
                 from /home/tom/click-kernel/linuxmodule/../include/click/array_memory.hh:3,
                 from /home/tom/click-kernel/linuxmodule/../include/click/vector.hh:4,
                 from /home/tom/click-kernel/linuxmodule/../include/click/args.hh:5,
                 from /home/tom/click-kernel/linuxmodule/../include/click/nameinfo.hh:4,
                 from /home/tom/click-kernel/linuxmodule/../lib/nameinfo.cc:21:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:237:2: error: expected identifier before string constant
  DEPRECATED = h_deprecated,
  ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:237:2: error: expected ‘}’ before string constant
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:237:2: error: expected unqualified-id before string constant
In file included from /home/tom/click-kernel/linuxmodule/../include/click/element.hh:8:0,
                 from /home/tom/click-kernel/linuxmodule/../include/click/router.hh:4,
                 from /home/tom/click-kernel/linuxmodule/../lib/nameinfo.cc:24:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘const String& Handler::name() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:64:9: error: ‘_name’ was not declared in this scope
  return _name;
         ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘uint32_t Handler::flags() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:71:9: error: ‘_flags’ was not declared in this scope
  return _flags;
         ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘void* Handler::user_data(int) const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:77:25: error: ‘_write_user_data’ was not declared in this scope
  return op == h_write ? _write_user_data : _read_user_data;
                         ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:77:44: error: ‘_read_user_data’ was not declared in this scope
  return op == h_write ? _write_user_data : _read_user_data;
                                            ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘void* Handler::read_user_data() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:82:9: error: ‘_read_user_data’ was not declared in this scope
  return _read_user_data;
         ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘void* Handler::write_user_data() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:87:9: error: ‘_write_user_data’ was not declared in this scope
  return _write_user_data;
         ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘bool Handler::readable() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:98:9: error: ‘_flags’ was not declared in this scope
  return _flags & h_read;
         ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘bool Handler::read_param() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:104:9: error: ‘_flags’ was not declared in this scope
  return _flags & h_read_param;
         ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘bool Handler::read_visible() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:113:10: error: ‘_flags’ was not declared in this scope
  return (_flags & (h_read | h_read_private)) == h_read;
          ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘bool Handler::writable() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:118:9: error: ‘_flags’ was not declared in this scope
  return _flags & h_write;
         ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘bool Handler::write_visible() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:127:10: error: ‘_flags’ was not declared in this scope
  return (_flags & (h_write | h_write_private)) == h_write;
          ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘bool Handler::allow_concurrent_handlers() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:138:17: error: ‘_flags’ was not declared in this scope
         return (_flags & h_nonexclusive);
                 ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘bool Handler::allow_concurrent_threads() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:144:17: error: ‘_flags’ was not declared in this scope
         return (_flags & h_nonexclusive);
                 ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In member function ‘bool Handler::raw() const’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:166:9: error: ‘_flags’ was not declared in this scope
  return _flags & h_raw;
         ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In static member function ‘static const Handler* Handler::blank_handler()’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:225:9: error: ‘the_blank_handler’ was not declared in this scope
  return the_blank_handler;
         ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: At global scope:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:247:14: error: ‘h_exclusive’ was not declared in this scope
  EXCLUSIVE = h_exclusive,
              ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:248:17: error: ‘h_nonexclusive’ was not declared in this scope
  NONEXCLUSIVE = h_nonexclusive
                 ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:259:64: error: non-member function ‘String __call_read(Element*, void*)’ cannot have cv-qualifier
     inline String __call_read(Element *e, void *new_user_data) const {
                                                                ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: In function ‘String __call_read(Element*, void*)’:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:261:9: error: ‘_read_hook’ was not declared in this scope
  return _read_hook.r(e, new_user_data);
         ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh: At global scope:
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:265:3: error: expected unqualified-id before ‘private’
   private:
   ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:271:7: warning: anonymous type with no linkage used to declare variable ‘<anonymous union> _read_hook’ with linkage
     } _read_hook;
       ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:275:7: warning: anonymous type with no linkage used to declare variable ‘<anonymous union> _write_hook’ with linkage
     } _write_hook;
       ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:284:13: error: expected unqualified-id before ‘const’
     Handler(const String & = String());
             ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:284:13: error: expected ‘)’ before ‘const’
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:287:46: error: non-member function ‘bool compatible(const Handler&)’ cannot have cv-qualifier
     inline bool compatible(const Handler &x) const;
                                              ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:289:5: error: ‘friend’ used outside of class
     friend class Router;
     ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:291:1: error: expected declaration before ‘}’ token
 };
 ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:271:7: warning: ‘_read_hook’ defined but not used [-Wunused-variable]
     } _read_hook;
       ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:275:7: warning: ‘_write_hook’ defined but not used [-Wunused-variable]
     } _write_hook;
       ^
/home/tom/click-kernel/linuxmodule/../include/click/handler.hh:282:27: warning: ‘the_blank_handler’ defined but not used [-Wunused-variable]
     static const Handler *the_blank_handler;
                           ^
make[5]: *** [/home/tom/click-kernel/linuxmodule/nameinfo.o] Error 1
make[4]: *** [_module_/home/tom/click-kernel/linuxmodule] Error 2
make[3]: *** [sub-make] Error 2
make[2]: *** [all] Error 2
make[2]: Leaving directory `/usr/src/linux-source-3.14'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/tom/click-kernel/linuxmodule'
make: *** [linuxmodule] Error 2
```

Thanks for the help,

Tom

**Comment by kohler** [comment]
I've gotten rid of the already-obsolete DEPRECATED constant.
